user nginx;
worker_processes auto;

events {
    worker_connections 1024;
}

http {
    include       mime.types;
    default_type  application/octet-stream;
    sendfile      on;
    gzip          on;
    gzip_static   on;
    gunzip        on;

    server {
        listen 8080;
        server_name _;

        # Match Uguu config defaults
        client_max_body_size 500m;

        root /app/dist/public;
        index index.html;

        location / {
            try_files $uri /index.html =404;
        }

        # Serve uploaded files from FILES_ROOT
        location /files/ {
            alias /var/www/files/;
            autoindex on;
            access_log off;
        }

        location ~* \.(?:js|css|png|jpg|jpeg|gif|ico|svg|avif)$ {
            expires 30d;
            access_log off;
        }

        location ~ \.php$ {
            include              fastcgi_params;
            fastcgi_param        SCRIPT_FILENAME $document_root$fastcgi_script_name;
            fastcgi_param        DOCUMENT_ROOT $document_root;
            fastcgi_index        index.php;
            fastcgi_buffers      16 16k;
            fastcgi_buffer_size  32k;
            fastcgi_pass         127.0.0.1:9000;
        }
    }
}
